// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Patisserie.Models;

[Table("Client")]
[Index("AdresseCourriel", Name = "UQ_Client_Email", IsUnique = true)]
public partial class Client
{
    [Key]
    [Column("Id_Client")]
    public int IdClient { get; set; }

    [Required]
    [StringLength(200)]
    [Unicode(false)]
    public string Nom { get; set; }

    [Required]
    [StringLength(200)]
    [Unicode(false)]
    public string Prenom { get; set; }

    [Required]
    [Column("Adresse_courriel")]
    [StringLength(200)]
    [Unicode(false)]
    public string AdresseCourriel { get; set; }

    [InverseProperty("IdClientNavigation")]
    public virtual ICollection<Commande> Commandes { get; set; } = new List<Commande>();
}