// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Patisserie.Models;

[Table("Commande")]
public partial class Commande
{
    [Key]
    [Column("Id_Commande")]
    public int IdCommande { get; set; }

    [Required]
    [StringLength(200)]
    [Unicode(false)]
    public string Nom { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string Description { get; set; }

    [Column("Id_Client")]
    public int IdClient { get; set; }

    [ForeignKey("IdClient")]
    [InverseProperty("Commandes")]
    public virtual Client IdClientNavigation { get; set; }

    [InverseProperty("IdCommandeNavigation")]
    public virtual ICollection<Imputation> Imputations { get; set; } = new List<Imputation>();

    [InverseProperty("IdCommandeNavigation")]
    public virtual ICollection<Utilise> Utilises { get; set; } = new List<Utilise>();

    [ForeignKey("IdCommande")]
    [InverseProperty("IdCommandes")]
    public virtual ICollection<Employe> IdEmployes { get; set; } = new List<Employe>();
}