// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Patisserie.Models;

[PrimaryKey("IdIngredient", "IdRecette")]
[Table("Compose")]
public partial class Compose
{
    [Key]
    [Column("Id_Ingredient")]
    public int IdIngredient { get; set; }

    [Key]
    [Column("Id_Recette")]
    public int IdRecette { get; set; }

    [Column("Quantite_Necessaire", TypeName = "decimal(10, 2)")]
    public decimal QuantiteNecessaire { get; set; }

    [ForeignKey("IdIngredient")]
    [InverseProperty("Composes")]
    public virtual Ingredient IdIngredientNavigation { get; set; }

    [ForeignKey("IdRecette")]
    [InverseProperty("Composes")]
    public virtual Recette IdRecetteNavigation { get; set; }
}