// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Patisserie.Models;

[Table("Employe")]
[Index("AdresseCourriel", Name = "UQ_Employe_Email", IsUnique = true)]
public partial class Employe
{
    [Key]
    [Column("Id_Employe")]
    public int IdEmploye { get; set; }

    [Required]
    [StringLength(200)]
    [Unicode(false)]
    public string Nom { get; set; }

    [Required]
    [StringLength(200)]
    [Unicode(false)]
    public string Prenom { get; set; }

    [Required]
    [Column("Adresse_courriel")]
    [StringLength(200)]
    [Unicode(false)]
    public string AdresseCourriel { get; set; }

    [InverseProperty("IdEmployeNavigation")]
    public virtual ICollection<Imputation> Imputations { get; set; } = new List<Imputation>();

    [ForeignKey("IdEmploye")]
    [InverseProperty("IdEmployes")]
    public virtual ICollection<Commande> IdCommandes { get; set; } = new List<Commande>();
}