// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Patisserie.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Patisserie.Models
{
    public partial interface ILaDouceLessardContextProcedures
    {
        Task<int> AjouterImputationAsync(DateOnly? date_Imputation, decimal? quantite_Reservee, int? id_Commande, int? id_Employe, int? id_Recette, int? id_Ingredient, int? id_Magasin, decimal? quantite_Imputee, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ObtenirCommandesParIngredientResult>> ObtenirCommandesParIngredientAsync(int? id_Ingredient, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<RechercherIngredientsResult>> RechercherIngredientsAsync(string recherche, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
