// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Patisserie.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Patisserie.Models
{
    public partial interface ILaDouceLessardContextProcedures
    {
        Task<int> Pro_AjouterImputationRecetteAsync(DateOnly? date_Imputation, decimal? quantite_Reservee, int? id_Commande, int? id_Employe, int? id_Recette, int? id_Magasin, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Pro_ObtenirCommandesParRecetteResult>> Pro_ObtenirCommandesParRecetteAsync(int? id_Recette, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Pro_RechercherRecettesResult>> Pro_RechercherRecettesAsync(string recherche, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> Pro_SupprimerCommandeAsync(int? id_Commande, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
