// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Patisserie.Models;

[Table("ImputationIngredient")]
public partial class ImputationIngredient
{
    [Key]
    [Column("Id_ImputationIngredient")]
    public int IdImputationIngredient { get; set; }

    [Column("Id_Imputation")]
    public int IdImputation { get; set; }

    [Column("Id_Ingredient")]
    public int IdIngredient { get; set; }

    [Column("Id_Magasin")]
    public int? IdMagasin { get; set; }

    [Column("Quantite_Imputee", TypeName = "decimal(10, 2)")]
    public decimal QuantiteImputee { get; set; }

    [ForeignKey("IdImputation")]
    [InverseProperty("ImputationIngredients")]
    public virtual Imputation IdImputationNavigation { get; set; }

    [ForeignKey("IdIngredient")]
    [InverseProperty("ImputationIngredients")]
    public virtual Ingredient IdIngredientNavigation { get; set; }

    [ForeignKey("IdMagasin")]
    [InverseProperty("ImputationIngredients")]
    public virtual Magasin IdMagasinNavigation { get; set; }
}