// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Patisserie.Models;

[Table("Imputation")]
public partial class Imputation
{
    [Key]
    [Column("Id_Imputation")]
    public int IdImputation { get; set; }

    [Column("Date_Imputation")]
    public DateOnly DateImputation { get; set; }

    [Column("Quantite_Reservee", TypeName = "decimal(10, 2)")]
    public decimal QuantiteReservee { get; set; }

    [Column("Id_Commande")]
    public int IdCommande { get; set; }

    [Column("Id_Employe")]
    public int IdEmploye { get; set; }

    [Column("Id_Recette")]
    public int IdRecette { get; set; }

    [ForeignKey("IdCommande")]
    [InverseProperty("Imputations")]
    public virtual Commande IdCommandeNavigation { get; set; }

    [ForeignKey("IdEmploye")]
    [InverseProperty("Imputations")]
    public virtual Employe IdEmployeNavigation { get; set; }

    [ForeignKey("IdRecette")]
    [InverseProperty("Imputations")]
    public virtual Recette IdRecetteNavigation { get; set; }
}