// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Patisserie.Models;

[Table("Ingredient")]
[Index("NumeroIdentification", Name = "UQ_Ingredient_Numero", IsUnique = true)]
public partial class Ingredient
{
    [Key]
    [Column("Id_Ingredient")]
    public int IdIngredient { get; set; }

    [Required]
    [StringLength(200)]
    [Unicode(false)]
    public string Description { get; set; }

    [Required]
    [Column("Numero_identification")]
    [StringLength(200)]
    [Unicode(false)]
    public string NumeroIdentification { get; set; }

    [InverseProperty("IdIngredientNavigation")]
    public virtual ICollection<Compose> Composes { get; set; } = new List<Compose>();

    [InverseProperty("IdIngredientNavigation")]
    public virtual ICollection<ImputationIngredient> ImputationIngredients { get; set; } = new List<ImputationIngredient>();

    [InverseProperty("IdIngredientNavigation")]
    public virtual ICollection<QuantiteStock> QuantiteStocks { get; set; } = new List<QuantiteStock>();

    [ForeignKey("IdIngredient")]
    [InverseProperty("IdIngredients")]
    public virtual ICollection<UniteDeMesure> IdUniteDeMesures { get; set; } = new List<UniteDeMesure>();
}