// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Patisserie.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Patisserie.Models
{
    public partial class LaDouceLessardContext
    {
        private ILaDouceLessardContextProcedures _procedures;

        public virtual ILaDouceLessardContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new LaDouceLessardContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public ILaDouceLessardContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class LaDouceLessardContextProcedures : ILaDouceLessardContextProcedures
    {
        private readonly LaDouceLessardContext _context;

        public LaDouceLessardContextProcedures(LaDouceLessardContext context)
        {
            _context = context;
        }

        public virtual async Task<int> Pro_AjouterImputationRecetteAsync(DateOnly? date_Imputation, decimal? quantite_Reservee, int? id_Commande, int? id_Employe, int? id_Recette, int? id_Magasin, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Date_Imputation",
                    Value = date_Imputation ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                new SqlParameter
                {
                    ParameterName = "Quantite_Reservee",
                    Precision = 10,
                    Scale = 2,
                    Value = quantite_Reservee ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "Id_Commande",
                    Value = id_Commande ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Id_Employe",
                    Value = id_Employe ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Id_Recette",
                    Value = id_Recette ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Id_Magasin",
                    Value = id_Magasin ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[Pro_AjouterImputationRecette] @Date_Imputation = @Date_Imputation, @Quantite_Reservee = @Quantite_Reservee, @Id_Commande = @Id_Commande, @Id_Employe = @Id_Employe, @Id_Recette = @Id_Recette, @Id_Magasin = @Id_Magasin", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<Pro_ObtenirCommandesParRecetteResult>> Pro_ObtenirCommandesParRecetteAsync(int? id_Recette, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Id_Recette",
                    Value = id_Recette ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<Pro_ObtenirCommandesParRecetteResult>("EXEC @returnValue = [dbo].[Pro_ObtenirCommandesParRecette] @Id_Recette = @Id_Recette", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<Pro_RechercherRecettesResult>> Pro_RechercherRecettesAsync(string recherche, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Recherche",
                    Size = 200,
                    Value = recherche ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<Pro_RechercherRecettesResult>("EXEC @returnValue = [dbo].[Pro_RechercherRecettes] @Recherche = @Recherche", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> Pro_SupprimerCommandeAsync(int? id_Commande, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Id_Commande",
                    Value = id_Commande ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[Pro_SupprimerCommande] @Id_Commande = @Id_Commande", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
