// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Patisserie.Models;

public partial class LaDouceLessardContext : DbContext
{
    public LaDouceLessardContext()
    {
    }

    public LaDouceLessardContext(DbContextOptions<LaDouceLessardContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Client> Clients { get; set; }

    public virtual DbSet<Commande> Commandes { get; set; }

    public virtual DbSet<Compose> Composes { get; set; }

    public virtual DbSet<Employe> Employes { get; set; }

    public virtual DbSet<Imputation> Imputations { get; set; }

    public virtual DbSet<Ingredient> Ingredients { get; set; }

    public virtual DbSet<Magasin> Magasins { get; set; }

    public virtual DbSet<QuantiteStock> QuantiteStocks { get; set; }

    public virtual DbSet<Recette> Recettes { get; set; }

    public virtual DbSet<UniteDeMesure> UniteDeMesures { get; set; }

    public virtual DbSet<Utilise> Utilises { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=bd-tinfo;Initial Catalog=1438952_AL;Integrated Security=True;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Client>(entity =>
        {
            entity.HasKey(e => e.IdClient).HasName("PK__Client__668DFF3FA5D023E5");
        });

        modelBuilder.Entity<Commande>(entity =>
        {
            entity.HasKey(e => e.IdCommande).HasName("PK__Commande__93349D6879FC6A45");

            entity.HasOne(d => d.IdClientNavigation).WithMany(p => p.Commandes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Commande__Id_Cli__0E6E26BF");
        });

        modelBuilder.Entity<Compose>(entity =>
        {
            entity.HasKey(e => new { e.IdIngredient, e.IdRecette }).HasName("PK__Compose__91D0C61B52C7195A");

            entity.HasOne(d => d.IdIngredientNavigation).WithMany(p => p.Composes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Compose__Id_Ingr__1AD3FDA4");

            entity.HasOne(d => d.IdRecetteNavigation).WithMany(p => p.Composes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Compose__Id_Rece__1BC821DD");
        });

        modelBuilder.Entity<Employe>(entity =>
        {
            entity.HasKey(e => e.IdEmploye).HasName("PK__Employe__9508084678F2CCA8");

            entity.HasMany(d => d.IdCommandes).WithMany(p => p.IdEmployes)
                .UsingEntity<Dictionary<string, object>>(
                    "Prepare",
                    r => r.HasOne<Commande>().WithMany()
                        .HasForeignKey("IdCommande")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__Prepare__Id_Comm__1F98B2C1"),
                    l => l.HasOne<Employe>().WithMany()
                        .HasForeignKey("IdEmploye")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__Prepare__Id_Empl__1EA48E88"),
                    j =>
                    {
                        j.HasKey("IdEmploye", "IdCommande").HasName("PK__Prepare__0C3B41904D2B7D16");
                        j.ToTable("Prepare");
                        j.IndexerProperty<int>("IdEmploye").HasColumnName("Id_Employe");
                        j.IndexerProperty<int>("IdCommande").HasColumnName("Id_Commande");
                    });
        });

        modelBuilder.Entity<Imputation>(entity =>
        {
            entity.HasKey(e => e.IdImputation).HasName("PK__Imputati__F5CB1BFEE2FDB5DB");

            entity.HasOne(d => d.IdCommandeNavigation).WithMany(p => p.Imputations)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Imputatio__Id_Co__114A936A");

            entity.HasOne(d => d.IdEmployeNavigation).WithMany(p => p.Imputations)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Imputatio__Id_Em__123EB7A3");

            entity.HasOne(d => d.IdRecetteNavigation).WithMany(p => p.Imputations)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Imputatio__Id_Re__1332DBDC");
        });

        modelBuilder.Entity<Ingredient>(entity =>
        {
            entity.HasKey(e => e.IdIngredient).HasName("PK__Ingredie__C39FEB49CBE608A2");

            entity.HasMany(d => d.IdUniteDeMesures).WithMany(p => p.IdIngredients)
                .UsingEntity<Dictionary<string, object>>(
                    "SeMesureEn",
                    r => r.HasOne<UniteDeMesure>().WithMany()
                        .HasForeignKey("IdUniteDeMesure")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__SeMesureE__Id_Un__236943A5"),
                    l => l.HasOne<Ingredient>().WithMany()
                        .HasForeignKey("IdIngredient")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__SeMesureE__Id_In__22751F6C"),
                    j =>
                    {
                        j.HasKey("IdIngredient", "IdUniteDeMesure").HasName("PK__SeMesure__F1B9452D141244BF");
                        j.ToTable("SeMesureEn");
                        j.IndexerProperty<int>("IdIngredient").HasColumnName("Id_Ingredient");
                        j.IndexerProperty<int>("IdUniteDeMesure").HasColumnName("Id_UniteDeMesure");
                    });
        });

        modelBuilder.Entity<Magasin>(entity =>
        {
            entity.HasKey(e => e.IdMagasin).HasName("PK__Magasin__A1268810F16EA1FD");
        });

        modelBuilder.Entity<QuantiteStock>(entity =>
        {
            entity.HasOne(d => d.IdIngredientNavigation).WithMany(p => p.QuantiteStocks)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Stock_Ingredient");

            entity.HasOne(d => d.IdMagasinNavigation).WithMany(p => p.QuantiteStocks)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Stock_Magasin");
        });

        modelBuilder.Entity<Recette>(entity =>
        {
            entity.HasKey(e => e.IdRecette).HasName("PK__Recette__24F2D524C052B8EB");
        });

        modelBuilder.Entity<UniteDeMesure>(entity =>
        {
            entity.HasKey(e => e.IdUniteDeMesure).HasName("PK__UniteDeM__226AE6423272B8BC");
        });

        modelBuilder.Entity<Utilise>(entity =>
        {
            entity.HasOne(d => d.IdCommandeNavigation).WithMany(p => p.Utilises)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Utilise_Commande");

            entity.HasOne(d => d.IdRecetteNavigation).WithMany(p => p.Utilises)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Utilise_Recette");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}