// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Patisserie.Models;

public partial class LaDouceLessardContext : DbContext
{
    public LaDouceLessardContext()
    {
    }

    public LaDouceLessardContext(DbContextOptions<LaDouceLessardContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Client> Clients { get; set; }

    public virtual DbSet<Commande> Commandes { get; set; }

    public virtual DbSet<Compose> Composes { get; set; }

    public virtual DbSet<Employe> Employes { get; set; }

    public virtual DbSet<Imputation> Imputations { get; set; }

    public virtual DbSet<ImputationIngredient> ImputationIngredients { get; set; }

    public virtual DbSet<Ingredient> Ingredients { get; set; }

    public virtual DbSet<Magasin> Magasins { get; set; }

    public virtual DbSet<QuantiteStock> QuantiteStocks { get; set; }

    public virtual DbSet<Recette> Recettes { get; set; }

    public virtual DbSet<UniteDeMesure> UniteDeMesures { get; set; }

    public virtual DbSet<Utilise> Utilises { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=LADOUCEURSTEVEN;Initial Catalog=LaDouceLessard;Integrated Security=True;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Client>(entity =>
        {
            entity.HasKey(e => e.IdClient).HasName("PK__Client__668DFF3F0FA5EAB5");
        });

        modelBuilder.Entity<Commande>(entity =>
        {
            entity.HasKey(e => e.IdCommande).HasName("PK__Commande__93349D685F556E52");

            entity.HasOne(d => d.IdClientNavigation).WithMany(p => p.Commandes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Commande__Id_Cli__4316F928");
        });

        modelBuilder.Entity<Compose>(entity =>
        {
            entity.HasKey(e => new { e.IdIngredient, e.IdRecette }).HasName("PK__Compose__91D0C61BB56573B0");

            entity.HasOne(d => d.IdIngredientNavigation).WithMany(p => p.Composes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Compose__Id_Ingr__4F7CD00D");

            entity.HasOne(d => d.IdRecetteNavigation).WithMany(p => p.Composes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Compose__Id_Rece__5070F446");
        });

        modelBuilder.Entity<Employe>(entity =>
        {
            entity.HasKey(e => e.IdEmploye).HasName("PK__Employe__95080846D2A1F6BF");

            entity.HasMany(d => d.IdCommandes).WithMany(p => p.IdEmployes)
                .UsingEntity<Dictionary<string, object>>(
                    "Prepare",
                    r => r.HasOne<Commande>().WithMany()
                        .HasForeignKey("IdCommande")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__Prepare__Id_Comm__5441852A"),
                    l => l.HasOne<Employe>().WithMany()
                        .HasForeignKey("IdEmploye")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__Prepare__Id_Empl__534D60F1"),
                    j =>
                    {
                        j.HasKey("IdEmploye", "IdCommande").HasName("PK__Prepare__0C3B4190F3E432DB");
                        j.ToTable("Prepare");
                        j.IndexerProperty<int>("IdEmploye").HasColumnName("Id_Employe");
                        j.IndexerProperty<int>("IdCommande").HasColumnName("Id_Commande");
                    });
        });

        modelBuilder.Entity<Imputation>(entity =>
        {
            entity.HasKey(e => e.IdImputation).HasName("PK__Imputati__F5CB1BFE3A2DA01E");

            entity.HasOne(d => d.IdCommandeNavigation).WithMany(p => p.Imputations)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Imputatio__Id_Co__45F365D3");

            entity.HasOne(d => d.IdEmployeNavigation).WithMany(p => p.Imputations)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Imputatio__Id_Em__46E78A0C");

            entity.HasOne(d => d.IdRecetteNavigation).WithMany(p => p.Imputations)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Imputatio__Id_Re__47DBAE45");
        });

        modelBuilder.Entity<ImputationIngredient>(entity =>
        {
            entity.HasKey(e => e.IdImputationIngredient).HasName("PK__Imputati__724F6C8FECE58ADF");

            entity.HasOne(d => d.IdImputationNavigation).WithMany(p => p.ImputationIngredients)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Imputatio__Id_Im__5FB337D6");

            entity.HasOne(d => d.IdIngredientNavigation).WithMany(p => p.ImputationIngredients)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Imputatio__Id_In__60A75C0F");

            entity.HasOne(d => d.IdMagasinNavigation).WithMany(p => p.ImputationIngredients).HasConstraintName("FK__Imputatio__Id_Ma__619B8048");
        });

        modelBuilder.Entity<Ingredient>(entity =>
        {
            entity.HasKey(e => e.IdIngredient).HasName("PK__Ingredie__C39FEB499FF5EE69");

            entity.HasMany(d => d.IdUniteDeMesures).WithMany(p => p.IdIngredients)
                .UsingEntity<Dictionary<string, object>>(
                    "SeMesureEn",
                    r => r.HasOne<UniteDeMesure>().WithMany()
                        .HasForeignKey("IdUniteDeMesure")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__SeMesureE__Id_Un__5812160E"),
                    l => l.HasOne<Ingredient>().WithMany()
                        .HasForeignKey("IdIngredient")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__SeMesureE__Id_In__571DF1D5"),
                    j =>
                    {
                        j.HasKey("IdIngredient", "IdUniteDeMesure").HasName("PK__SeMesure__F1B9452DCC74B8AA");
                        j.ToTable("SeMesureEn");
                        j.IndexerProperty<int>("IdIngredient").HasColumnName("Id_Ingredient");
                        j.IndexerProperty<int>("IdUniteDeMesure").HasColumnName("Id_UniteDeMesure");
                    });
        });

        modelBuilder.Entity<Magasin>(entity =>
        {
            entity.HasKey(e => e.IdMagasin).HasName("PK__Magasin__A126881072188D0E");
        });

        modelBuilder.Entity<QuantiteStock>(entity =>
        {
            entity.HasOne(d => d.IdIngredientNavigation).WithMany(p => p.QuantiteStocks)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Stock_Ingredient");

            entity.HasOne(d => d.IdMagasinNavigation).WithMany(p => p.QuantiteStocks)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Stock_Magasin");
        });

        modelBuilder.Entity<Recette>(entity =>
        {
            entity.HasKey(e => e.IdRecette).HasName("PK__Recette__24F2D5240D831CB1");
        });

        modelBuilder.Entity<UniteDeMesure>(entity =>
        {
            entity.HasKey(e => e.IdUniteDeMesure).HasName("PK__UniteDeM__226AE6427AC19D0E");
        });

        modelBuilder.Entity<Utilise>(entity =>
        {
            entity.HasOne(d => d.IdCommandeNavigation).WithMany(p => p.Utilises)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Utilise_Commande");

            entity.HasOne(d => d.IdRecetteNavigation).WithMany(p => p.Utilises)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Utilise_Recette");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}