// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Patisserie.Models;

[Table("LogTransaction")]
public partial class LogTransaction
{
    [Key]
    [Column("Id_Log")]
    public int IdLog { get; set; }

    [Column("Date_Log", TypeName = "datetime")]
    public DateTime DateLog { get; set; }

    [Required]
    [Column("Nom_Procedure")]
    [StringLength(100)]
    public string NomProcedure { get; set; }

    [Required]
    [StringLength(50)]
    public string Operation { get; set; }

    [Required]
    [Column("Table_Cible")]
    [StringLength(100)]
    public string TableCible { get; set; }

    [Column("Id_Cible")]
    public int? IdCible { get; set; }

    [Required]
    [StringLength(20)]
    public string Statut { get; set; }

    [StringLength(4000)]
    public string Message { get; set; }
}