// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Patisserie.Models;

[Table("Magasin")]
[Index("Nom", Name = "UQ_Magasin_Nom", IsUnique = true)]
public partial class Magasin
{
    [Key]
    [Column("Id_Magasin")]
    public int IdMagasin { get; set; }

    [Required]
    [StringLength(200)]
    [Unicode(false)]
    public string Nom { get; set; }

    [InverseProperty("IdMagasinNavigation")]
    public virtual ICollection<QuantiteStock> QuantiteStocks { get; set; } = new List<QuantiteStock>();
}