// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Patisserie.Models
{
    public partial class ObtenirCommandesParIngredientResult
    {
        public int Id_Commande { get; set; }
        [StringLength(200)]
        public string NomCommande { get; set; }
        [StringLength(200)]
        public string DescriptionCommande { get; set; }
        public int Id_Recette { get; set; }
        [StringLength(200)]
        public string NomRecette { get; set; }
        [StringLength(200)]
        public string DescriptionRecette { get; set; }
        public int Quantite_Prevue { get; set; }
        [Column("Quantite_Necessaire", TypeName = "decimal(10,2)")]
        public decimal Quantite_Necessaire { get; set; }
        [Column("QuantiteTotaleTheorique", TypeName = "decimal(21,2)")]
        public decimal? QuantiteTotaleTheorique { get; set; }
    }
}
