// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Patisserie.Models
{
    public partial class Pro_ObtenirCommandesParRecetteResult
    {
        public int Id_Commande { get; set; }
        [StringLength(200)]
        public string NomCommande { get; set; }
        [StringLength(200)]
        public string DescriptionCommande { get; set; }
        public int Quantite_Prevue { get; set; }
    }
}
