// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Patisserie.Models
{
    public partial class Pro_RechercherRecettesResult
    {
        public int Id_Recette { get; set; }
        [StringLength(200)]
        public string Nom { get; set; }
        [StringLength(200)]
        public string Description { get; set; }
    }
}
