// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Patisserie.Models;

[PrimaryKey("IdIngredient", "IdMagasin")]
[Table("QuantiteStock")]
public partial class QuantiteStock
{
    [Key]
    [Column("Id_Ingredient")]
    public int IdIngredient { get; set; }

    [Key]
    [Column("Id_Magasin")]
    public int IdMagasin { get; set; }

    [Column("QuantiteStock", TypeName = "decimal(10, 2)")]
    public decimal QuantiteStock1 { get; set; }

    [ForeignKey("IdIngredient")]
    [InverseProperty("QuantiteStocks")]
    public virtual Ingredient IdIngredientNavigation { get; set; }

    [ForeignKey("IdMagasin")]
    [InverseProperty("QuantiteStocks")]
    public virtual Magasin IdMagasinNavigation { get; set; }
}