// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Patisserie.Models;

[Table("Recette")]
[Index("Nom", Name = "UQ_Recette_Nom", IsUnique = true)]
public partial class Recette
{
    [Key]
    [Column("Id_Recette")]
    public int IdRecette { get; set; }

    [Required]
    [StringLength(200)]
    [Unicode(false)]
    public string Nom { get; set; }

    [Required]
    [StringLength(200)]
    [Unicode(false)]
    public string Description { get; set; }

    [InverseProperty("IdRecetteNavigation")]
    public virtual ICollection<Compose> Composes { get; set; } = new List<Compose>();

    [InverseProperty("IdRecetteNavigation")]
    public virtual ICollection<Imputation> Imputations { get; set; } = new List<Imputation>();

    [InverseProperty("IdRecetteNavigation")]
    public virtual ICollection<Utilise> Utilises { get; set; } = new List<Utilise>();
}