// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Patisserie.Models
{
    public partial class RechercherIngredientsResult
    {
        public int Id_Ingredient { get; set; }
        [StringLength(200)]
        public string Numero_identification { get; set; }
        [StringLength(200)]
        public string Description { get; set; }
        [Column("QuantiteStockTotale", TypeName = "decimal(38,2)")]
        public decimal QuantiteStockTotale { get; set; }
        [StringLength(8000)]
        public string Magasins { get; set; }
    }
}
