// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Patisserie.Models;

[Table("UniteDeMesure")]
public partial class UniteDeMesure
{
    [Key]
    [Column("Id_UniteDeMesure")]
    public int IdUniteDeMesure { get; set; }

    [Required]
    [StringLength(200)]
    [Unicode(false)]
    public string Nom { get; set; }

    [ForeignKey("IdUniteDeMesure")]
    [InverseProperty("IdUniteDeMesures")]
    public virtual ICollection<Ingredient> IdIngredients { get; set; } = new List<Ingredient>();
}