// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Patisserie.Models;

[PrimaryKey("IdCommande", "IdRecette")]
[Table("Utilise")]
public partial class Utilise
{
    [Key]
    [Column("Id_Commande")]
    public int IdCommande { get; set; }

    [Key]
    [Column("Id_Recette")]
    public int IdRecette { get; set; }

    [Column("Quantite_Prevue")]
    public int QuantitePrevue { get; set; }

    [ForeignKey("IdCommande")]
    [InverseProperty("Utilises")]
    public virtual Commande IdCommandeNavigation { get; set; }

    [ForeignKey("IdRecette")]
    [InverseProperty("Utilises")]
    public virtual Recette IdRecetteNavigation { get; set; }
}