// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Patisserie.Models;

[Keyless]
public partial class VueIngredientQuantitePrevu
{
    [Column("Id_Commande")]
    public int IdCommande { get; set; }

    [Required]
    [StringLength(200)]
    [Unicode(false)]
    public string Description { get; set; }

    [Column("Quantite_Prevue")]
    public int QuantitePrevue { get; set; }

    [Column("Id_Ingredient")]
    public int IdIngredient { get; set; }
}